### ISSUE TITLE
Cant get to work on Linux Mint 18.3 64 bit

### ISSUE THREAD

**Issue by ianrolfe** [radiomanV/TL866#10]
I know there are some issues with the wrapper on 64 bit, is it possible to get it to work? The UDEV rule seems to be triggering because I added a command to touch a file when it does and that seems to be OK.
I tried installing libusb 32 bit with sudo apt-get install libusb-1.0-0:i386 but it says its already installed. 
If I run Minipro on the command line I get a message:
```
ian@Asus01 ~/Wine $ wine MiniPro.exe 
fixme:win:RegisterDeviceNotificationA (hwnd=0x10086, filter=0x4ec710,flags=0x00000000) returns a fake device notification handle!
```

Is there anything else I could try? I'm sorry but despite having used linux for many years I'm a bit of a newbie when it comes to udev and Wine.....
```
ian@Asus01 ~/Wine $ uname -a
Linux Asus01 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by radiomanV** [comment]
Seem like the setupapi.dll is not loaded at all! 
The dll name is very important! it must be exactly setupapi.dll and must be located in the same directory with the minipro.exe! 
Also what minipro version you have? you must use the suplied .dll version according with the minipro software version you use.

**Comment by ianrolfe** [comment]
I have MiniPro 6.60 and I downloaded the setupapi_v660.dll file:
```
ian@Asus01 ~/Wine $ ls -l
total 8276
drwxrwxr-x 5 ian ian    4096 Dec 25  2015 ATMEGA8_LED
-rw-rw-r-- 1 ian ian     732 Dec 17 15:27 config.dat
drwxrwxr-x 4 ian ian    4096 Dec 25  2015 drv
drwxrwxr-x 2 ian ian    4096 Dec 25  2015 img
-rw-rw-r-- 1 ian ian 4005888 May  8  2017 InfoIC.dll
-rw-rw-r-- 1 ian ian       4 Dec 12 19:00 language.dat
-rwxrwxr-x 1 ian ian 1024000 May  8  2017 MiniPro.exe
-rw-rw-r-- 1 ian ian 2672960 Jun 29  2012 MiniProHelp.chm
-rw-rw-r-- 1 ian ian   26520 May  8  2017 Serial25Index.dat
drwxrwxr-x 3 ian ian    4096 Dec 25  2015 Serialnumber
-rw-rw-r-- 1 ian ian   30850 Dec 13 17:40 setupapi.dll
-rwxrwxr-x 1 ian ian  221184 Jun 26  2012 Uninstall.exe
-rw-rw-r-- 1 ian ian  312348 May  8  2017 update.dat
-rwxrwxr-x 1 ian ian  143360 Dec 25  2015 UsbDrvInstall.exe
```

**Comment by ianrolfe** [comment]
```
ian@Asus01 ~/Wine $ ls -l ~/Minipro/
total 344
-rw-rw-r-- 1 ian ian  30850 Dec 13 17:40 setupapi_v660.dll
-rw-rw-r-- 1 ian ian 312348 May  8  2017 update.dat

```

**Comment by ianrolfe** [comment]
![screenshot from 2017-12-17 23-45-32](https://user-images.githubusercontent.com/6229711/34085196-75e6fac0-e384-11e7-8b2c-6077df89d21e.png)

**Comment by radiomanV** [comment]
Looks ok for me.
Now please:
`$ file ./setupapi.dll `
`$ ldd ./setupapi.dll `
`$ objdump -p ./setupapi.dll | grep NEEDED`
and paste here the output of each command. I think that the setupapi.dll is not what it looks like, meaning a dyanmic library.
Just installed Mint 18.3 in a VM and installed only wine. After that checked for libusb:i386 and libudev:i386  wich were alreday installed. Copied setupapi.dll to the minipro folder and:
`wine  ./MiniPro.exe`
and bam! it loaded just ok! sure you must add a udev rule for libusb can access the tl866 device without root permission but these are details.

**Comment by ianrolfe** [comment]
Well your diagnosis was unerring - file revealed it to be a HTML document. I must have "save link as.." rather than clicking the link and using the download button. I re-downloaded the dll properly and sure enough its working fine! Thanks for your help, I'm just sorry to have wasted your time!

**Comment by radiomanV** [comment]
Good, i'm glad you figured out by yourself! When you posted the console results i immediately saw    the file size(30k) wich it should be ~80k but wanted to give you a hint (file command).
So it must be how you downloaded the file wich is somewhat funny! plain text(html) with .dll extension! meh.. strange!
Regarding the wasted time no problem, it was a good memory exercise!
