### ISSUE TITLE
Modify or write new firmware

### ISSUE THREAD

**Issue by PeterBortas** [radiomanV/TL866#11]
Has any work been done towards modifying the FW or writing your own? 

We just had a discussion about unsupported chips in https://github.com/vdudouyt/minipro/issues/90 and came to the conclusion that using the default FW for dumping old PROMs for Mame probably isn't the way forward.

**Comment by JohnDMcMaster** [comment]
Bump. It looks like you are still actively developing the utilities and have pushed a lot of documentation. But I don't see anything (public) towards an open firmware. Can you please give some insight as to your project roadmap?

Peter: feel free to reach out to me directly as well if you want to collaborate.

**Comment by JohnDMcMaster** [comment]
Can you provide some documentation on bit banging? I don't see them in the open souce minipro project

**Comment by radiomanV** [comment]
I have no clear documentation yet (only a draft text file), but i have experimented with these bit banging primitives and what can i say is that you can set the zif i/o lines direction, toggle zif i/o lines for all 40 pins, also you can set the pin drivers VPP, VCC, GND on supported pins but from what i know you can't set voltages on these pins (or at least i'm not found any primitive for this).
Right now i'm quite busy with the forked version of Linux minipro software here: [https://gitlab.com/radiomanV/minipro/tree/master](https://gitlab.com/radiomanV/minipro/tree/master) .
I have added couples of features, improvements and bug fixes. Maybe i will add a logic ic tester if i have enough time.

If you want to play, here is the draft:[https://gist.github.com/radiomanV/69ef14c704325bfa58339f2ae73a900f](https://gist.github.com/radiomanV/69ef14c704325bfa58339f2ae73a900f)

**Comment by JohnDMcMaster** [comment]
Thanks, will take a look! BTW forgot if I mentioned, but a number of us have grouped together in freenode IRC room #proghq

**Comment by PeterBortas** [comment]
We should probably also mention that the open source firmware for tl866 has made good progress and is available here: https://github.com/ProgHQ/open-tl866

**Comment by iddq** [comment]
Where could I find info about the protocol used by the original fw?

**Comment by pyopower** [comment]
I don't know about the protocol ... I can pass you the original file for
the last update.
