### ISSUE TITLE
MiniPro TL866 II Plus

### ISSUE THREAD

**Issue by levin-kelevra** [radiomanV/TL866#14]
Hi!
Can you provide how to use TL866II Plus v7.07?
setupapi.dll not work.

**Comment by radiomanV** [comment]
The setupapi.dll is designed to work with minipro v6.x not 7.x which is another software implementation.
You can't use the setupapi.dll for now, the new software must be investigated (aka disassembled) and setupapi.dll must be reimplemented.
Theres's no action you can take for now.

**Comment by radiomanV** [comment]
A new version of setupapi.dll wrapper for TL866II Plus V7.x was released.
Check the wine directory.

**Comment by levin-kelevra** [comment]
It works!
Thank you!

**Comment by artelse** [comment]
Just to confirm, the wrapper works fine on my Linux Mint system with the new TL866II plus latest firmware. Thanks @radiomanV !

**Comment by serhi999** [comment]
At me TL866 And plus does not work in wine! . The programmer received a couple of days ago, updated the firmware in Windows. The following error in the console:
err:module:import_dll Loading library WINUSB.DLL (which is needed by L"C:\\Xgpro\\Xgpro.exe") failed (error c000012f).
err:module:LdrInitializeThunk Main exe initialization for L"C:\\Xgpro\\Xgpro.exe" failed, status c0000135

**Comment by radiomanV** [comment]
I think that you use wine64 right? if so please install 32 bit wine and try again.

**Comment by serhi999** [comment]
installed the wine32 OS is selected XP. file winusb.dll copy from windows dir. Now the program starts but does not see the device. when installing the driver, you can see that it was not installed
wine .\\UsbDriverIntall.exe
err:setupapi:SetupCopyOEMInfW Could not add catalog

**Comment by serhi999** [comment]
I followed these instructions. the program does not see the device.

**Comment by radiomanV** [comment]
Something is wrong there.
Please do this in terminal:
`wine ./MiniPro.exe`
And paste here the entire output. Maybe there are missing libs.

**Comment by serhi999** [comment]
My program version 7.32

**Comment by serhi999** [comment]
userse@mci-620:~/.wine/drive_c/Xgpro$ wine .\\Xgpro.exeuserse@mci-620:~/.wine/drive_c/Xgpro$ wine .\\Xgpro.exe

**Comment by serhi999** [comment]
no information in the console.

**Comment by radiomanV** [comment]
You do something wrong!
Copy this in the console `wine ~/.wine/drive_c/Xgpro/Xgpro.exe`
And paste here the output...

**Comment by serhi999** [comment]
wine ~/.wine/drive_c/Xgpro/Xgpro.exe
Dll Loaded.
Found Xgpro v7.32
Base Address = 0x00400000
Code section = 0x00401000,0x00201C00
Open Devices found at 0x00461E70
Close Devices found at  0x00461C60
Usb Handle found at  0x00696B74
WinUsb Handle found at  0x0069E0E0
Devices count found at  0x0069DAD8
Open devices.
Close devices.
RegisterDeviceNotifications hWnd=1E02E04

**Comment by serhi999** [comment]
install libusb-1.0.0-dev:i386

**Comment by radiomanV** [comment]
This is correct! the programmer should work in this condition. Libusb is installed?

**Comment by radiomanV** [comment]
Nevermind! you figured out!

**Comment by serhi999** [comment]
all problems due to 64 bit OS. now everything works correctly! Many thanks for the possibility of working in Linux with the device!!
