### ISSUE TITLE
setupapi.dll wrapper for TL866II Plus V8.x

### ISSUE THREAD

**Issue by fabbrimichele** [radiomanV/TL866#19]
Hi and thank you for the great job.
I was wondering if there is any plan for providing a setupapi.dll for the version 8.30  of Xgpro.

Cheers,
Michele

**Comment by radiomanV** [comment]
Currently usb low level usb wrapper it's working with 8.x xgpro version. Do you have any issues with it? Yes i know the readme says 7.x but i forgot to update it.

**Comment by fabbrimichele** [comment]
Thanks for your reply.

I have the following configuration:
- ubuntu 18
- kernel version 4.15.18-041518-generic
- wine-3.0 (Ubuntu 3.0-1ubuntu1)
- Xgpro v8.30, with the latest firmware in the TL866II plus device (working in Windows)

I followed the following step:
1. I copied the file setupapi.dll in the folder ~/.wine/drive_c/Xgpro
2. created a new rule file '/etc/udev/rules.d/51-minipro.rules' with the following content:
```SUBSYSTEMS=="usb", ATTRS{idVendor}=="a466", ATTRS{idProduct}=="0a53", GROUP="plugdev", MODE="0666"```

When I attach the TL866II plus device the kernel reports:
```
[  116.590118] usb 1-1: new full-speed USB device number 7 using xhci_hcd
[  116.740853] usb 1-1: New USB device found, idVendor=a466, idProduct=0a53
[  116.740866] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[  116.740875] usb 1-1: Product: Xingong XGecu USB Prog.. Device
[  116.740884] usb 1-1: Manufacturer: Xingong Electronicg Co.. 
```
Xgpro UI reports: 
```Hardware Interface Ver: No Device!```

and Wine reports:
```
michele@nuc:~/.wine/drive_c/Xgpro$ wine Xgpro.exe 
002c:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002c:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002c:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
```

**Comment by radiomanV** [comment]
This appear like the setupapi.dll is not loading at all. This is 64bit Ubuntu right?

**Comment by fabbrimichele** [comment]
I tried again with your ```setupapi.dll``` download from here, I tried to program a AT28C256 and it worked like a charm. 
For some reason I had forgotten to replace the original dll with yours.
I'm sorry to have wasted your time and thank you very much for your support.

**Comment by radiomanV** [comment]
Good! just installed Ubuntu 18 on a virtual machine to test this. Installed wine from the Ubuntu software center (or something like that, I'm not using Ubuntu currently) added that udev rule and bam! worked like a charm.

> I'm sorry to have wasted your time and thank you very much for your support.    

No worries this was a good exercise! i have not installed/used ubuntu for years.

**Comment by fabbrimichele** [comment]
Thanks again and have a nice evening!
