### ISSUE TITLE
Request: update wine dll for V6.10

### ISSUE THREAD

**Issue by stevenhoneyman** [radiomanV/TL866#2]
I tried your wine dll but it doesn't seem to work for the current minipro V6.10 - any chance it could be updated please?

**Comment by radiomanV** [comment]
Hi Steven, the wine dll wrapper actually really works in 6.10!
Please give me more details about your issue (linux distro you use etc.).
Thanks!

**Comment by stevenhoneyman** [comment]
That's good news! I'll keep trying then.

I'm using Arch Linux with distro-provided wine package, and minipro downloaded today from autoelectric. The unit works fine using the native command line linux program that someone else wrote, so I don't think it's anything to do with permissions. It compiles fine too, but I get the same as testing with your compiled dll - nothing at all happens, it's as if I'd never even plugged in the cable. "Hardware Interface Ver: No Device!" in the status bar.

I'll see if I can get some useful debugging output from wine now that I know the dll should work.

**Comment by stevenhoneyman** [comment]
Hmm WINEDEBUG might make this easier to fix.
On a clean 32-bit wine root:

```
$ WINEDEBUG=setupapi WINEARCH=win32 WINEPREFIX="/ramdisk/winetest/wine32" wine ./minipro/MiniPro.exe 
trace:setupapi:SetupDiGetClassDevsExW {85980d83-32b9-4ba1-8fdf-12a711b99ca2} (null) (nil) 0x00000012 (nil) (null) (nil)
warn:setupapi:SetupDiGetClassDevsExW unsupported flags 00000002
trace:setupapi:SetupDiCreateDeviceInfoListExW {85980d83-32b9-4ba1-8fdf-12a711b99ca2} (nil) (null) (nil)
trace:setupapi:SETUPDI_EnumerateInterfaces 0x133468, {85980d83-32b9-4ba1-8fdf-12a711b99ca2}, (null), 00000012
trace:setupapi:SetupDiEnumDeviceInterfaces 0x133468, (nil), {85980d83-32b9-4ba1-8fdf-12a711b99ca2}, 0, 0x32f200
trace:setupapi:SetupDiDestroyDeviceInfoList 0x133468
fixme:win:RegisterDeviceNotificationA (hwnd=0x1005e, filter=0x4ea0a0,flags=0x00000000) returns a fake device notification handle!
```

And default 64-bit:
```
$ WINEDEBUG=setupapi WINEPREFIX="/ramdisk/winetest/wine64" wine ./minipro/MiniPro.exe 
trace:setupapi:SetupDiGetClassDevsExW {85980d83-32b9-4ba1-8fdf-12a711b99ca2} (null) (nil) 0x00000012 (nil) (null) (nil)
warn:setupapi:SetupDiGetClassDevsExW unsupported flags 00000002
trace:setupapi:SetupDiCreateDeviceInfoListExW {85980d83-32b9-4ba1-8fdf-12a711b99ca2} (nil) (null) (nil)
trace:setupapi:SETUPDI_EnumerateInterfaces 0x1334e8, {85980d83-32b9-4ba1-8fdf-12a711b99ca2}, (null), 00000012
trace:setupapi:SetupDiEnumDeviceInterfaces 0x1334e8, (nil), {85980d83-32b9-4ba1-8fdf-12a711b99ca2}, 0, 0x32f200
trace:setupapi:SetupDiDestroyDeviceInfoList 0x1334e8
fixme:win:RegisterDeviceNotificationA (hwnd=0x80058, filter=0x4ea0a0,flags=0x00000000) returns a fake device notification handle!
```

**Comment by radiomanV** [comment]
aha!
1. you must have the setupapi.dll in the same directory with minipro.exe
2. you should have an udev rule in /etc/udev/rules.d (you should have one if you use that cli software).
3.64bit OS; well here is a little issue. The minipro.exe being a 32bit app. the dll must be 32 bit also and to have 32bit libusb and libudev version installed.
Seems like the setupapi.dll is not loaded at all!
try this:
wine ./MiniPro.exe in console and paste here the output.
The funny thing is that i have actually tested it in Arch both 32/64bit and no issue, heh!

**Comment by stevenhoneyman** [comment]
woohoo!
```
Dll Loaded.
Open devices.
Close devices.
RegisterDeviceNotifications hWnd=100684
```

I was missing lib32-libcap. Doh!
Thanks for the help/hints

**Comment by radiomanV** [comment]
well this sounds good! i definitely recognize that debug info!
that libcap must be arch specific, good to know.
