### ISSUE TITLE
Fails to run under Wine/Wineskin on OS X with setupapi.dll

### ISSUE THREAD

**Issue by sorphin** [radiomanV/TL866#28]
Fails to run under Wine/Wineskin on OS X with setupapi.dll  Both minipro and xgpro run fine under wine 5.2-5.6 under OS X but once I copy in the setupapi.dll from here, they fail to launch with the same previous messages that it can't be found by user32.dll, etc.

MiniPro 6.85:
0009:err:module:import_dll Loading library SETUPAPI.dll (which is needed by L"C:\\MiniPro\\MiniPro.exe") failed (error c000012f).
0009:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\USER32.dll") failed (error c000012f).
0009:err:module:import_dll Library USER32.dll (which is needed by L"C:\\MiniPro\\MiniPro.exe") not found
0009:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0009:err:module:import_dll Library user32.dll (which is needed by L"C:\\windows\\system32\\imm32.dll") not found
0009:err:seh:raise_exception Unhandled exception code c0000005 flags 0 addr 0x7bc54d74

XgproV1008:
0009:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\USER32.dll") failed (error c000012f).
0009:err:module:import_dll Library USER32.dll (which is needed by L"C:\\Xgpro\\Xgpro.exe") not found
0009:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0009:err:module:import_dll Library user32.dll (which is needed by L"C:\\windows\\system32\\WINSPOOL.DRV") not found
0009:err:module:import_dll Library WINSPOOL.DRV (which is needed by L"C:\\Xgpro\\Xgpro.exe") not found
0009:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0009:err:module:import_dll Library user32.dll (which is needed by L"C:\\windows\\system32\\shlwapi.dll") not found
0009:err:seh:raise_exception Unhandled exception code c0000005 flags 0 addr 0x7bc54d74

**Comment by radiomanV** [comment]
Unfortunately you can't use this wrapper under OSX at this time. This wrapper (a winelib) is compilee under linux and uses some linux low level subsystems.For example udev which is not available under mac ecosystem.

**Comment by sorphin** [comment]
Do you have any future plans to make it so?

**Comment by radiomanV** [comment]
Unfortunately I'm not a Mac developer so I don't think so. I don't even own a Macbook to test something. Maybe i should ask a mac developer to take a look on this who knows.

**Comment by sorphin** [comment]
Understood.
