### ISSUE TITLE
Duplicate file TL866_Updater/QT/Dumper.bin

### ISSUE THREAD

**Issue by nospam2000** [radiomanV/TL866#29]
There are two files which only differ in upper/lowercase characters:
 1. TL866_Updater/QT/**Dumper.bin**
 2. TL866_Updater/QT/**dumper.bin**

This gives an error when cloning from git on system which use a case insensitive filesystem like MacOS or Windows:
```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:
  'TL866_Updater/QT/Dumper.bin'
  'TL866_Updater/QT/dumper.bin'
```

Please delete the wrong file

**Comment by radiomanV** [comment]
I don't know when that shadow file was introduced, perhaps from one of my Linux machine. Anyway i fixed this.
Thanks!
