### ISSUE TITLE
Can't build under Ubuntu 14.04 LTS 32bits

### ISSUE THREAD

**Issue by braselectron** [radiomanV/TL866#3]
I am would like to use minipro TL866 under wine-staging / Ubuntu 14.04 LTS 32bits
but I need to install the usb driver using @radiomanV wine solution.

My System Software / Hardware Information

Hardware:
Processor: Intel Core 2 6300 @ 1.87GHz (2 Cores), 
Motherboard: Gigabyte 965P-DS3, 
Chipset: Intel 82P965/G965 + ICH8/R, 
Memory: 8192MB, 
Disk: 500GB Western Digital WD5000BPKT-0, 
Graphics: eVGA NVIDIA GeForce GT 610 2048MB, 
Audio: Realtek ALC888, 
Monitor: SyncMaster P2370, Native Resolution: 1920x1080
Network: Marvell 88E8056 PCI-E Gigabit

Software:
OS: Ubuntu 14.04, 
Kernel: 3.13.0-91-generic (i686), 
Desktop: Unity 7.2.6, 
Display Server: X Server 1.15.1, 
Display Driver: nouveau 1.0.10, 
OpenGL: 3.3 
Mesa 10.1.3 Gallium 0.4, 
Compiler: GCC 4.8 + Clang 3.4-1ubuntu3, 
File-System: ext4, Screen 

Installed deb packages:
ii  gcc                       4:4.8.2-1ubun   i386         GNU C compiler
ii  make                    3.81-8.2ubunt   i386         An utility for Directing compilation.
ii  wine                     <none>              <none>    (no description available)
ii  wine-staging        1.9.7~ubuntu1    i386        official WineHQ build of the popular
ii  libusb-1.0-0-dev  2:1.0.17-1ubu     i386        userspace USB programming library dev
ii  libusb-dev            2:0.1.12-23.3     i386         userspace USB programming library dev
ii  wine-staging        1.9.7~ubuntu1    i386        official WineHQ build of the popular 
ii  wine-staging-dev 1.9.7~ubuntu1    i386        official WineHQ build of the popular
ii  winehq-staging    1.9.7~ubuntu1    i386        official WineHQ build of the popular

I am using PPA wine-staging because of issues with video drivers and wine install

I am trying to build the driver wrap to be able to run minipro with wine on Ubuntu 14.04 LTS 32bits but my git clone just does not work

```
~/TL866/wine$ make
winegcc -c      -o usb.o usb.c
winegcc: gcc-4.7 failed
make: *** [usb.o] Error 2
```

Looking at the Makefile it seems like it is missing parameters.

Need help.

**Comment by radiomanV** [comment]
Hi,
I can reproduce your issue, installed wine-stagging seem that the winegcc is the problem and not the makefile. It can't run properly because of missing gcc dependencies; if you run winegcc it throws the same error.

The solution is to install the gcc-4.7 multilib.
`
sudo apt-get install g++-4.7-multilib
`
and voila

`
~/Development/usb$ wine --version
wine-1.9.15 (Staging)
`
`
~/Development/usb$ make
`
`winegcc -c      -o usb.o usb.c`
`winegcc -shared usb.spec -o usb.dll.so usb.o      -lusb-1.0 -ludev -lpthread  
`
Done.

**Comment by braselectron** [comment]
Dear radiomanV,

You are right!

I actually did have a g++ installed but I `--reinstall` the g++-4.7-multilib

I believe that some other package I installed or removed/purged corrupted the compiler and finally did the compiling correct without errors. Great!

But I still had a problem which I debugged running the MiniPro.exe from terminal:

` /opt/wine-staging/bin/wine MiniPro.exe`

This is useful because I can see debug information on the terminal console.  And the information was this:

```
fixme:module:load_dll Loader redirect from L"SETUPAPI.dll" to L"setupapi.dll"
Dll Loaded.       <- good news!!!
Open devices.  
Close devices.
libusbx: error [_get_usbfs_fd] libusbx couldn't open USB device /dev/bus/usb/004/003: 
Permission denied  <- problem detected!!!
libusbx: error [_get_usbfs_fd] libusbx requires write access to USB device nodes.
RegisterDeviceNotifications hWnd=D010A4
Close devices.
```

So I believe that was solved the problem is this:

I changed the order of the parameters in the "50-minipro.rules" (not sure yet that this matters)

```
SUBSYSTEMS=="usb", ATTRS{idVendor}=="04d8", ATTRS{idProduct}=="e11c", MODE="0666",
 GROUP="users"
```

And used "sudo" to trigger the new udev with the TL866 "plugged in".
`sudo udevadm trigger`

Can I start a new tread/issue here to ask @radiomanV  questions about the project or should I use the blog:
http://www.eevblog.com/forum/blog/eevblog-411-minipro-tl866-universal-programmer-review ?

**Comment by radiomanV** [comment]
`
libusbx: error [_get_usbfs_fd] libusbx couldn't open USB device /dev/bus/usb/004/003: 
Permission denied  <- problem detected!!!
libusbx: error [_get_usbfs_fd] libusbx requires write access to USB device nodes.
`
this mean that you don't have permision to acces the usb device and must add an udev rule
`
SUBSYSTEMS=="usb", ATTRS{idVendor}=="04d8", ATTRS{idProduct}=="e11c", MODE="0666",
 GROUP="users"
`
You could try changing GROUP="users" with GROUP="plugdev", depending on what distro you use.

Regarding to your questions you can start a new thread/issue here no problem.
