### ISSUE TITLE
Late versions of setupapi.dll not working for Linux Mint 19.3

### ISSUE THREAD

**Issue by jonsag** [radiomanV/TL866#37]
After installing XGPro 11.30 under wine 6.0.1 on two machines running Linux Mint 20.2 and 19.3, only the former works.

When starting on the LM19.3 with the [latest version of setupapi.dll](https://github.com/radiomanV/TL866/raw/b417f91de85eac026b468c91daca2235a65d6dd7/wine/setupapi.dll):

`0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0068:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0068:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0070:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0070:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0060:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0060:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0068:err:vulkan:wine_vk_init Failed to load libvulkan.so.1.
002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\USER32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library USER32.dll (which is needed by L"C:\\Program Files\\XGPro-11.x\\Xgpro.exe") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\WINSPOOL.DRV") failed (error c000007b).
0024:err:module:import_dll Library WINSPOOL.DRV (which is needed by L"C:\\Program Files\\XGPro-11.x\\Xgpro.exe") not found
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\combase.dll") failed (error c000007b).
0024:err:module:import_dll Loading library combase.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library ole32.dll (which is needed by L"C:\\windows\\system32\\shcore.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\shcore.dll") failed (error c000007b).
0024:err:module:import_dll Loading library shcore.dll (which is needed by L"C:\\windows\\system32\\shlwapi.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\shlwapi.dll") failed (error c000007b).
0024:err:module:import_dll Loading library shlwapi.dll (which is needed by L"C:\\windows\\system32\\SHELL32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\SHELL32.dll") failed (error c000007b).
0024:err:module:import_dll Library SHELL32.dll (which is needed by L"C:\\Program Files\\XGPro-11.x\\Xgpro.exe") not found
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\combase.dll") failed (error c000007b).
0024:err:module:import_dll Loading library combase.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library ole32.dll (which is needed by L"C:\\windows\\system32\\shcore.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\shcore.dll") failed (error c000007b).
0024:err:module:import_dll Loading library shcore.dll (which is needed by L"C:\\windows\\system32\\SHLWAPI.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\SHLWAPI.dll") failed (error c000007b).
0024:err:module:import_dll Loading library SHLWAPI.dll (which is needed by L"C:\\Program Files\\XGPro-11.x\\Xgpro.exe") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\UxTheme.dll") failed (error c000007b).
0024:err:module:import_dll Loading library UxTheme.dll (which is needed by L"C:\\Program Files\\XGPro-11.x\\Xgpro.exe") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\combase.dll") failed (error c000007b).
0024:err:module:import_dll Loading library combase.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library ole32.dll (which is needed by L"C:\\Program Files\\XGPro-11.x\\Xgpro.exe") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\combase.dll") failed (error c000007b).
0024:err:module:import_dll Loading library combase.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library ole32.dll (which is needed by L"C:\\windows\\system32\\OLEAUT32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\OLEAUT32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library OLEAUT32.dll (which is needed by L"C:\\Program Files\\XGPro-11.x\\Xgpro.exe") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\imm32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library imm32.dll (which is needed by L"C:\\windows\\system32\\comctl32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\comctl32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library comctl32.dll (which is needed by L"C:\\windows\\system32\\comdlg32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\combase.dll") failed (error c000007b).
0024:err:module:import_dll Loading library combase.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library ole32.dll (which is needed by L"C:\\windows\\system32\\shcore.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\shcore.dll") failed (error c000007b).
0024:err:module:import_dll Loading library shcore.dll (which is needed by L"C:\\windows\\system32\\shlwapi.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\shlwapi.dll") failed (error c000007b).
0024:err:module:import_dll Loading library shlwapi.dll (which is needed by L"C:\\windows\\system32\\shell32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\shell32.dll") failed (error c000007b).
0024:err:module:import_dll Library shell32.dll (which is needed by L"C:\\windows\\system32\\comdlg32.dll") not found
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\combase.dll") failed (error c000007b).
0024:err:module:import_dll Loading library combase.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library ole32.dll (which is needed by L"C:\\windows\\system32\\shcore.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\shcore.dll") failed (error c000007b).
0024:err:module:import_dll Loading library shcore.dll (which is needed by L"C:\\windows\\system32\\shlwapi.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\shlwapi.dll") failed (error c000007b).
0024:err:module:import_dll Loading library shlwapi.dll (which is needed by L"C:\\windows\\system32\\comdlg32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\comdlg32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\winspool.drv") failed (error c000007b).
0024:err:module:import_dll Library winspool.drv (which is needed by L"C:\\windows\\system32\\comdlg32.dll") not found
0024:err:module:import_dll Loading library comdlg32.dll (which is needed by L"C:\\windows\\system32\\oledlg.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\combase.dll") failed (error c000007b).
0024:err:module:import_dll Loading library combase.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library ole32.dll (which is needed by L"C:\\windows\\system32\\oledlg.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\oledlg.dll") failed (error c000007b).
0024:err:module:import_dll Loading library oledlg.dll (which is needed by L"C:\\Program Files\\XGPro-11.x\\Xgpro.exe") failed (error c000007b).
0024:err:module:import_dll Loading library SETUPAPI.dll (which is needed by L"C:\\Program Files\\XGPro-11.x\\Xgpro.exe") failed (error c000012f).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\mpr.dll") failed (error c000007b).
0024:err:module:import_dll Loading library mpr.dll (which is needed by L"C:\\windows\\system32\\WININET.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\combase.dll") failed (error c000007b).
0024:err:module:import_dll Loading library combase.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library ole32.dll (which is needed by L"C:\\windows\\system32\\shcore.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\shcore.dll") failed (error c000007b).
0024:err:module:import_dll Loading library shcore.dll (which is needed by L"C:\\windows\\system32\\shlwapi.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\shlwapi.dll") failed (error c000007b).
0024:err:module:import_dll Loading library shlwapi.dll (which is needed by L"C:\\windows\\system32\\shell32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\shell32.dll") failed (error c000007b).
0024:err:module:import_dll Library shell32.dll (which is needed by L"C:\\windows\\system32\\WININET.dll") not found
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\combase.dll") failed (error c000007b).
0024:err:module:import_dll Loading library combase.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library ole32.dll (which is needed by L"C:\\windows\\system32\\shcore.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\shcore.dll") failed (error c000007b).
0024:err:module:import_dll Loading library shcore.dll (which is needed by L"C:\\windows\\system32\\shlwapi.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\shlwapi.dll") failed (error c000007b).
0024:err:module:import_dll Loading library shlwapi.dll (which is needed by L"C:\\windows\\system32\\WININET.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\WININET.dll") failed (error c000007b).
0024:err:module:import_dll Loading library WININET.dll (which is needed by L"C:\\Program Files\\XGPro-11.x\\Xgpro.exe") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\combase.dll") failed (error c000007b).
0024:err:module:import_dll Loading library combase.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library ole32.dll (which is needed by L"C:\\windows\\system32\\gdiplus.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\combase.dll") failed (error c000007b).
0024:err:module:import_dll Loading library combase.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library ole32.dll (which is needed by L"C:\\windows\\system32\\shcore.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\shcore.dll") failed (error c000007b).
0024:err:module:import_dll Loading library shcore.dll (which is needed by L"C:\\windows\\system32\\shlwapi.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\shlwapi.dll") failed (error c000007b).
0024:err:module:import_dll Loading library shlwapi.dll (which is needed by L"C:\\windows\\system32\\gdiplus.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\gdiplus.dll") failed (error c000007b).
0024:err:module:import_dll Loading library gdiplus.dll (which is needed by L"C:\\Program Files\\XGPro-11.x\\Xgpro.exe") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\combase.dll") failed (error c000007b).
0024:err:module:import_dll Loading library combase.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library ole32.dll (which is needed by L"C:\\windows\\system32\\OLEACC.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\combase.dll") failed (error c000007b).
0024:err:module:import_dll Loading library combase.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library ole32.dll (which is needed by L"C:\\windows\\system32\\oleaut32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\oleaut32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library oleaut32.dll (which is needed by L"C:\\windows\\system32\\OLEACC.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\OLEACC.dll") failed (error c000007b).
0024:err:module:import_dll Loading library OLEACC.dll (which is needed by L"C:\\Program Files\\XGPro-11.x\\Xgpro.exe") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\IMM32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library IMM32.dll (which is needed by L"C:\\Program Files\\XGPro-11.x\\Xgpro.exe") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\msacm32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library msacm32.dll (which is needed by L"C:\\windows\\system32\\WINMM.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\combase.dll") failed (error c000007b).
0024:err:module:import_dll Loading library combase.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\ole32.dll") failed (error c000007b).
0024:err:module:import_dll Loading library ole32.dll (which is needed by L"C:\\windows\\system32\\WINMM.dll") failed (error c000007b).
0024:err:module:import_dll Loading library setupapi.dll (which is needed by L"C:\\windows\\system32\\user32.dll") failed (error c000012f).
0024:err:module:import_dll Loading library user32.dll (which is needed by L"C:\\windows\\system32\\WINMM.dll") failed (error c000007b).
0024:err:module:import_dll Loading library WINMM.dll (which is needed by L"C:\\Program Files\\XGPro-11.x\\Xgpro.exe") failed (error c000007b).
0024:err:module:LdrInitializeThunk Importing dlls for L"C:\\Program Files\\XGPro-11.x\\Xgpro.exe" failed, status c0000135`

When starting with the version from commit#[ fce3cdf427](https://github.com/radiomanV/TL866/raw/fce3cdf4270d5e4b6e850843dc81048cbd95aacd/wine/setupapi.dll) it starts ok:

`0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0064:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0064:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
006c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
006c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
005c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
005c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0064:err:vulkan:wine_vk_init Failed to load libvulkan.so.1.
002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0024:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0024:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
Dll Loaded.
Found Xgpro v11.30
Base Address = 0x00400000
Code section = 0x00401000,0x0024B000
Open Devices found at 0x004ADAF0
Close Devices found at  0x004AD8E0
Usb Handle found at  0x007065B0
WinUsb Handle found at  0x0071C31C
Devices count found at  0x00719A00
00c8:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
00c8:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0024:fixme:font:freetype_set_outline_text_metrics failed to read full_nameW for font L"Ani"!
Open devices.
Close devices.
RegisterDeviceNotifications hWnd=1006E4
0100:fixme:ver:GetCurrentPackageId (0195FEF0 00000000): stub
`

Wine version on both machines:

`$ wine --version
wine-6.0.1`

Qt on LM20.2:
`$ qtdiag
qt5ct: using qt5ct plugin
Qt 5.12.8 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 9.3.0) on "xcb" 
OS: Linux Mint 20.2 [linux version 5.4.0-81-generic]
...`

Qt on LM19.3:
`$ qtdiag
QGLXContext: Failed to create dummy context
Qt 5.9.5 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.4.0) on "xcb" 
OS: Linux Mint 19.3 [linux version 5.4.0-81-generic]
...`

On the LM20.2 it loads ok with the latest version of setupapi.dll

/jon

**Comment by radiomanV** [comment]
Yeah, that dll was compiled with winegcc under wine 6.17, Arch 64 bit and perhaps there is something fishy between the two worlds. Anyway, i (re)compiled it under Mint 19.3 with wine 6.0.1 (needed some conditionals about libusb API version; the debian libusb is quite old) but finally i succeeded to compile and run the resulted dll without errors.   
Please test the new dll and repply here.  
Thank you.

**Comment by jonsag** [comment]
I have tried compiling it myself, but haven't been successful.
I will get back to you.
/jon

**Comment by jonsag** [comment]
So, seems to work on both machines.
Starts up, and looks ok.
Haven't been able to try with the TL866 connected yet, though.
Thanks for your work.
/jon

**Comment by jonsag** [comment]
I can now confirm the present setupapi.dll works with the TL866II Plus programmer on my Linux Mint 19.3.
Thanks for the quick fix of this.
However, do you have some pointers on how to compile it for myself?

I get this: 
`$ make

winegcc -c  -m32 -mincoming-stack-boundary=2 -o setupapi.o setupapi.c
In file included from setupapi.c:7:0:
/usr/include/libusb-1.0/libusb.h:70:10: fatal error: windows.h: No such file or directory
 #include <windows.h>
          ^~~~~~~~~~~
compilation terminated.
winegcc: /usr/bin/gcc failed
Makefile:31: recipe for target 'setupapi.o' failed
make: *** [setupapi.o] Error 2
`

**Comment by radiomanV** [comment]
This is a bit tricky. Installed a fresh Mint 19.3 Mate in a Vbox machine and this is what i did to compile ok:   
```
wget -nc https://dl.winehq.org/wine-builds/winehq.key
sudo -H gpg -o /etc/apt/trusted.gpg.d/winehq.key.gpg --dearmor winehq.key
sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main' 
sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport && sudo apt update
sudo apt install build-essential winehq-stable wine-stable-dev libudev-dev:i386 libusb-1.0-0-dev:i386 libc6-dev:i386 g++-multilib
```
Hope it helps.

**Comment by jonsag** [comment]
Thanks again.
Tried it, but got too many unresolved dependencies.
Will not try any further, since it works well anyway for me.

`$ sudo apt install build-essential winehq-stable wine-stable-dev libudev-dev:i386 libusb-1.0-0-dev:i386 libc6-dev:i386 g++-multilib

Reading package lists... Done
Building dependency tree       
Reading state information... Done
winehq-stable is already the newest version (6.0.1~focal-1).
build-essential is already the newest version (12.8ubuntu1.1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 g++-multilib : Depends: gcc-multilib (= 4:9.3.0-1ubuntu2) but it is not going to be installed
                Depends: g++-9-multilib (>= 9.3.0-3~) but it is not going to be installed
 libc6-dev : Breaks: libc6-dev:i386 (!= 2.31-0ubuntu9.3) but 2.31-0ubuntu9.2 is to be installed
 libc6-dev:i386 : Depends: libc6:i386 (= 2.31-0ubuntu9.2) but 2.31-0ubuntu9.3 is to be installed
                  Depends: libc-dev-bin:i386 (= 2.31-0ubuntu9.2)
                  Breaks: libc6-dev (!= 2.31-0ubuntu9.2) but 2.31-0ubuntu9.3 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.`

**Comment by radiomanV** [comment]
Yeah, perhaps you have already installed another version of these. You should install these packages one by one but, anyway i'm glad that you  are happy.

**Comment by jonsag** [comment]
I truly am!
:-)
