### ISSUE TITLE
setupapi.dll wrapper not loading with Wine on Ubuntu with Xgpro version 11.30

### ISSUE THREAD

**Issue by rodneygray** [radiomanV/TL866#38]
0009:err:module:import_dll Loading library SETUPAPI.dll (which is needed by L"C:\\xgpro\\Xgpro.exe") failed (error c000012f).
0009:err:module:LdrInitializeThunk Importing dlls for L"C:\\xgpro\\Xgpro.exe" failed, status c0000135

If I remove setupapi.dll, the software starts but has no communication with the TL866ii.

**Comment by radiomanV** [comment]
Perhaps you do not have installed the 32 bit needed libraries. As i don't offer any packages you must install them by hand. I assume that you have a 64 bit Ubuntu right?
so check this:
`ldd ./setupapi.dll`
or `readelf -a ./setupapi.dll | grep NEEDED`
it will tell you the needed libraries which are only two: libusb and libudev. Please  install the 32 bit version of these like this:
`sudo apt install libusb-1.0-0:i386 libudev1:i386`
Then copy (if you don't did it already) the whole content of udev directory (from this repo) to `/etc/udev/rules.d/`
and reload the udev rules with `sudo udevadm trigger`
At this point if the wine is installed you can launch the Xgpro with `wine ./Xgpro.exe`
Normally in Ubuntu and derivates you don't need to manually install the above libs, it is enough to only install the wine package. 
Also please tell me what version of Ubuntu do you have and your wine version (`wine --version`).
Thanks.

**Comment by Wawavoun** [comment]
Hello there,

I use last version of Ubuntu wine (wine --version report 5.0) and XGpro install and works smoothly.

I remove all wine packages and empty user .wine directory then install wine 6.0.2 (last version for Ubuntu focal on wine repository) then XGpro refuse to install directly complaining about user32.dll and setupapi.dll not starting.

At this moment setupapi.dll was in the same directory that XGpro setup program.
If I remove this file from this place the setup run longer and did not complain about dll but hang.
It seems he is working on fonts (but I am unsure about that) and waiting even a long time do not give success.
Library etc... are ok.

Strangely If I only upgrade from wine 5.0 to wine 6.0.2 using apt then things seems continue to work normally (installation and usage)...

Okay I have a solution but it seems here that XGpro and setupapi.dll are not working on a clean wine > 6.0 install 
Thanks for help.

Regards.
Philippe

**Comment by Wawavoun** [comment]
Found a solution...
Seems really to be linked to a font problem because installing fonts-wine package solve it.

Regards.
Philippe

**Comment by radiomanV** [comment]
Thanks Philippe, seems to be a wine related issue after all. I never encounter this issue, perhaps because i always install the `devel` packages with `--install-recommends` flag (Linux Mint). I'll add your fix in the docs.

**Comment by CodeAsm** [comment]
I had a similair issue wich seemed to relate to user32 and ole32 dll not being found (yet they where there.)

> Perhaps you do not have installed the 32 bit needed libraries. As i don't offer any packages you must install them by hand. I assume that you have a 64 bit Ubuntu right? so check this: `ldd ./setupapi.dll` or `readelf -a ./setupapi.dll | grep NEEDED` it will tell you the needed libraries which are only two: libusb and libudev. Please install the 32 bit version of these ...

For my Arch install:
```sh
sudo pacman -S lib32-libusb
```
resolved my issue and the ldd command is something i should know, and I like it. it indeed showed 
```sh
	libusb-1.0.so.0 => not found
```
and now is found (some adress is shown, like the rest.
