### ISSUE TITLE
MiniPro in wine under lubuntu (16.10)

### ISSUE THREAD

**Issue by indyucoder** [radiomanV/TL866#7]
Hi, just installed MiniPro 6.60 in wine under lubuntu (16.10)
in your readme better update rule name because 50-udev-default.rules have the following rule 
  ... SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", MODE="0664"

:> udevadm test $(udevadm info -q path -n /dev/bus/usb/003/003)
...
Reading rules file: /lib/udev/rules.d/50-udev-default.rules
Reading rules file: /etc/udev/rules.d/51-minipro.rules
...

**Comment by radiomanV** [comment]
And your point is? name concern? rule standard? please explain moore!

**Comment by indyucoder** [comment]
In my system 50-udev-default.rules is evaluated after 50-minipro.rules so TL866 USB is mounted with permission flags set to 664 (read only for non root users) and MiniPro can't use it.
Using any number > 50 in the name ensures that minipro.rules override udev default.
Maybe other Linux distros have different udev rules, but to make Minipro working on Ubuntu 16.xx you need to change the rule file name.

**Comment by radiomanV** [comment]
Ah! yes, now i can see your point! Because i did not have any issue yet with this rule name and i tested this on many distros both 32/64 bit. This must be something new in udev or else.
Thanks to pointing me out into problem. I will update the readme to reflect this new issue.

**Comment by HoracioDos** [comment]
Hello!
I've updated to V6.60 right now and checked udev rules once again. My distro is Ubuntu based on 16.04 (Mint 18.1 Serena) and the udev file starting with '50' works fine.

/etc/udev/rules.d/50-minipro.rules

SUBSYSTEMS=="usb", ATTRS{idVendor}=="04d8", ATTRS{idProduct}=="e11c", TAG+="udev-acl", TAG+="uaccess", OWNER="root"

Something changed from 16.04 to 16.10

**Comment by radiomanV** [comment]
Ok. Anyway i updated the ReadMe file to 51-minipro.rules. Also the Linux Mint 18.1 is the current distro i use. I checked this on Arch/Manjaro/Ubuntu/Xubuntu and no problem, so let it as 51-minipro.rules for a while with the initial rule; if someone is having troubles i will update it again.
