### ISSUE TITLE
Compiling Updater?

### ISSUE THREAD

**Issue by LightningStalker** [radiomanV/TL866#9]
How do I compile the QT updater?  There's no instructions, no makefile, what do I do?

**Comment by LightningStalker** [comment]
Ok, nvm.  My unfamiliarity with `qmake` and `QtCreator` and being in the wrong directory nearly had me throwing a fit.  If anyone else needs to know, you have to run `qmake -makefile` in the QT directory to get a Linux binary.

**Comment by radiomanV** [comment]
Hi,
You must install Qt creator (Windows or Linux version, don't know your os) and open the project file (*.pro) then from the ide you can compile the project. Anyway this Qt version of the updater is quite outdated,  i have plan to update it but i don't know when.
[Here](https://www.qt.io/download-open-source/?hsCtaTracking=f977210e-de67-475f-a32b-65cec207fd03%7Cd62710cd-e1db-46aa-8d4d-2f1c1ffdacea) is the windows version, for Linux version check your package manager for it.

**Comment by LightningStalker** [comment]
No no, I got it to compile using `qmake`.  Now however I'm getting a `Filesize error` trying to open `firmwareA.bin` in the updater.

**Comment by LightningStalker** [comment]
It wants a `firmware.dat`, but I can't get it out of the software.  It's an `installer.exe` and I don't have Windows.

**Comment by LightningStalker** [comment]
Ok finally got it.  `MiniProV660setup.exe` is itself a rar archive.  I just made a new directory and ran `unrar` from there and out popped the `update.dat`.
